### ISSUE TITLE
[feature request] more async parameters may be configurable

### ISSUE THREAD

**Issue by huhongbo** [influxdata/influxdb-ruby#107]
Now some async parameters are not configurable
MAX_POST_POINTS = 1000
MAX_QUEUE_SIZE = 10_000
NUM_WORKER_THREADS = 3
SLEEP_INTERVAL = 5

**Comment by BarthV** [comment]
:+1:

**Comment by BarthV** [comment]
This issue is critical for us now :)

**Comment by dmke** [comment]
I will make the async paramaters configurable in the next days.
