### ISSUE TITLE
Default for time_precision differs from InfluxDB docs

### ISSUE THREAD

**Issue by felixbuenemann** [influxdata/influxdb-ruby#118]
The [InfluxDB 0.9 docs](https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html) mention that the default for time_precision is nanoseconds, unless specified otherwise. The ruby client defaults to a precision of seconds unless specified explicitly.

The difference in the behavior has caused me quite a headache debugging why my metrics were not showing up when sending nanoseconds without explicitly defining `time_precision: 'n'` when connecting to influxdb.

Was there a specific reason to choose a different default in the ruby client?

**Comment by dmke** [comment]
I think the most probable answer is that Ruby time classes are second-based. Plugging a timestamp into `Time.at(i)` will work without any further modification of the timestamp value.

As far as I can tell, the current default value was introduced in 5bbe96b, maybe @toddboom can shed some light on this?

For now, I'll close this ticket. (FWIW, influxdata/influxdb#6041 will change the default of the server to "an intelligent guess", soon)
