### ISSUE TITLE
Client should refuse to send empty tag values to InfluxDB

### ISSUE THREAD

**Issue by radcool** [influxdata/influxdb-ruby#124]
Considering that sending an InfluxDB line with empty tag values such as (notice the empty **ident** tag):

    syslog,host=fwtpcore1b,ident= message=\"BLAHBLAHBLAH\" 1449233580

will result in InfluxDB returning a **missing tag value** error, I would say that the Ruby client should omit tags with empty values in the line altogether.

I have come upon this issue in cases where Syslog message were received with no **ident** field while using Fluentd with the **fluent-plugin-influxdb** output plugin.

**Comment by dmke** [comment]
Seems like both the [Python](https://github.com/influxdata/influxdb-python/blob/master/influxdb/line_protocol.py#L113-L114) and the [Go client](https://github.com/influxdata/influxdb/blob/master/models/points.go#L1368) do this as well.

So I'm all for a consistent behaviour.

**Comment by dmke** [comment]
Version 0.2.6 is now available containing this fix.
