### ISSUE TITLE
InfluxDB insert fails, but write_points returns successfully

### ISSUE THREAD

**Issue by xiic** [influxdata/influxdb-ruby#128]
When sending a ~~invalid~~ valid, but not executable query, write_point(s) returns successfuly(!).

### Cause:
When sending an invalid write request to InfluxDB, the database answers with `HTTP 200 OK` and the error in the message body. Only if `HTTP 204 No Content` is sent, the request was executed successfully.

See: https://docs.influxdata.com/influxdb/v0.10/guides/writing_data/

### Bugfix:
In method `post` in file `lib/influxdb/client/http.rb`: Change `Net::HTTPSuccess` (2xx) to `Net::HTTPNoContent` (204)

**Comment by dmke** [comment]
Can you elaborate on "valid, but not executable", i.e. can you share a query which I could integrate into the test suite?

**Comment by xiic** [comment]
This happened after I ran out of disk space and the database files got corrupted (0.9.6 or 0.10). I can't reproduce it with the current 0.12.1 release, though.

I was just quoting the docs (https://docs.influxdata.com/influxdb/v0.12/guides/writing_data/):
> If it’s HTTP 204 No Content, success! If it’s HTTP 200 OK, InfluxDB understood the request but couldn’t complete it. The body of the response will contain additional error information.

Maybe the docs are outdated?

**Comment by dmke** [comment]
Hm, no I think the docs are correct. A successful write returns 204 (no content).

I've changed master to reflect that fact (1424aa4). I will later/tomorrow release a 0.3.0 version (since it's *kindofabreaking* change)

**Comment by dmke** [comment]
v0.3.0 is now released.
