### ISSUE TITLE
Question: SQL Injection

### ISSUE THREAD

**Issue by jeffdeville** [influxdata/influxdb-ruby#142]
Any suggestions on how to mitigate the risk of dangerous commands being injected?  Since we're just creating strings here, I'm assuming that this would amount to regex's to be applied to string components that are not trusted. If so, does such a thing exist, or could I easily drop someone's database if they permit any kind of dashboard filtering?

**Comment by dmke** [comment]
There's currently no check (neither for security nor sanity) built into this gem; every request given to `InfluxDB::Client#query` is sent straight to the server. Note that using the line protocol (`#write_point`/`#write_points`), only inserts should be possible.

If you want a starting point for input sanitation on queries, I encourage you to have a look at [palkan/influxer](https://github.com/palkan/influxer), especially the [`Influxer::Relation` class](https://github.com/palkan/influxer/blob/master/lib/influxer/metrics/relation.rb). That gem also does no sanitation, but it defines a nice abstraction of the query language which could easier be extended.

To mitigate a malicious (or accidental) `DROP DATABASE` et.al., you should create a non-privileged user, see the [InfluxDB docs on this matter](http://docs.influxdata.com/influxdb/v0.12/administration/authentication_and_authorization/#user-types-and-their-privileges). You could go as far as creating a seperate InfluxDB user for you user-facing code, which just has `READ` privileges.

**Comment by jeffdeville** [comment]
Very helpful!  I think I'll go the non-priveleged user route, thanks!

**Comment by dmke** [comment]
No problem!
