### ISSUE TITLE
Global Config

### ISSUE THREAD

**Issue by anthonator** [influxdata/influxdb-ruby#143]
Being able to specify config globally would make this gem a little more user friendly.

i.e.
```ruby
InfluxDB.configure do |config|
  config.host ["influxdb1.domain.com", "influxdb2.domain.com"]

  ...

end

InfluxDB.create_database('example_database')

# or

client = InfluxDB.client
client.create_database('example_database')
```

**Comment by dmke** [comment]
I wouldn't introduce a global configuration to this gem, as globals are notoriuously hard to test.

If you really need a global configuration, you can easily build a client factory and tailor it to your needs:

```ruby
class InfluxFactory < InfluxDB::Client
  class << self
    def defaults
      # return static hash,
      # or read from YAML file,
      # or ...
    end

    def client
      @client ||= new defaults
    end

    # assuming we're using Rails, add all (or only some) convenience methods
    if respond_to?(:delegate)
      [
        InfluxDB::Query::Core,
        InfluxDB::Query::Cluster,
        InfluxDB::Query::Database,
        InfluxDB::Query::User,
        InfluxDB::Query::ContinuousQuery,
        InfluxDB::Query::RetentionPolicy,
      ].each do |mod|
        delegate *mod.public_instance_methods, to: :client
      end
    end
  end
end
```

and substitute `InfluxFactory` for `InfuxDB` in your examples.

**Comment by anthonator** [comment]
It looks like `influxdb-rails` does basically what I proposed. Also looks like it was created by the `influxdata` team. Would you be interested in pointing to this in the README?

**Comment by anthonator** [comment]
Nevermind, looks a little more magical than I realized. Automatically reports stuff from your controllers.

Still, it provides some of the "global" functionality I was looking for.
