### ISSUE TITLE
Data in PointValue is not being properly escaped

### ISSUE THREAD

**Issue by lisinge** [influxdata/influxdb-ruby#144]
The `map` method in [PointValue](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/point_value.rb#L39) is never called. It was called in the `data_to_string` method before but has since been removed.

**Comment by dmke** [comment]
Yikes, sorry for that!

Somehow the original fix got lost (might have been merge conflicts...). I just updated the code and will release v0.3.1 when Travis is finished.

**Comment by dmke** [comment]
Version [0.3.1](https://rubygems.org/gems/influxdb) is now available.

**Comment by lisinge** [comment]
Thanks!
