### ISSUE TITLE
Writing data with less than second precision

### ISSUE THREAD

**Issue by jchauncey** [influxdata/influxdb-ruby#145]
So I am trying to write data with either millisecond or nanosecond precision and neither works. 

If I try to generate an integer that represents millisecond precision (since epoch): 

```
timestamp = (Time.now.to_f * 1000).to_i
```

I get the following error:

```
time outside range 1677-09-21 00:12:43.145224192 +0000 UTC - 2262-04-11 23:47:16.854775807 +0000 UTC
```

I am trying to do what the tests show but that doesn't seem to be working

**Comment by jchauncey** [comment]
Here is the spec that I was following https://github.com/influxdata/influxdb-ruby/blob/master/spec/influxdb/cases/write_points_spec.rb#L104

**Comment by dmke** [comment]
This might be a bug in the test, I will have a closer look tomorrow.

Which version of InfluxDB were you testing against?

**Comment by jchauncey** [comment]
0.13

**Comment by dmke** [comment]
I believe the test is indeed faulty: `precision: "m"` indicates **minutes**, not milliseconds (which would be `ms`), see ["duration units"](https://docs.influxdata.com/influxdb/v0.13/query_language/spec/#durations) in the language spec.

**Comment by jchauncey** [comment]
Yeah I tried it with ms too and same error.

**Comment by jchauncey** [comment]
The weird thing that happens is if I dont send any timestamp value and let Influx handle that I end up with second precision.

**Comment by jchauncey** [comment]
So I figured out the issue I think. Basically I am trying to write a bunch of data to 1 database. Some of that data is coming from telegraf and I think its resolution (even though I have it configured differently) is to the second. 

If I create a new database and write the data with the ruby client with millisecond precision everything seems to work just fine.

**Comment by jchauncey** [comment]
closing this issue as i figured out my problem.
