### ISSUE TITLE
0.3.2 breaks support for ruby 1.9.3

### ISSUE THREAD

**Issue by rubycut** [influxdata/influxdb-ruby#148]
https://github.com/influxdata/influxdb-ruby/commit/5e8774487b333085fb3acce1bdf635f8859b56d3#commitcomment-17727691

**Comment by dmke** [comment]
Actually, Ruby 1.9.3 support is broken since 12dbb05 (Gem version 0.1.9).

**Comment by dmke** [comment]
As noted in the issue comments:

> Actually, this was a problem with the .gemspec: When built under Ruby 2.1+, it didn't add a runtime dependency ("cause") the gem... When you then gem install influxdb, it doesn't include "cause", and you'll get a LoadError: cannot load such file -- cause.
> 
> As it turns out, the code base actually still works with Ruby 1.9.3 -- and starting with 0.3.4, I've reconsidered Ruby 1.9 support (at least for 0.3.x releases).
> 
> Long story short: as long as you don't install 0.2.4 - 0.3.3 under Ruby 1.9, you should be fine.
>  Add a line note
>
