### ISSUE TITLE
Can't specify [RESAMPLE [EVERY <interval>] [FOR <interval>]] for CQs

### ISSUE THREAD

**Issue by jeffdeville** [influxdata/influxdb-ruby#149]
Looking at the code:

`clause = ["CREATE CONTINUOUS QUERY #{name} ON #{database} BEGIN", query, "END"].join("\n")`

There's just no way to do this at the moment, other than to build the query ourselves, and execute it.

**Comment by dmke** [comment]
([code ref](https://github.com/influxdata/influxdb-ruby/blob/v0.3.2/lib/influxdb/query/continuous_query.rb#L14))

Well... *no way* isn't exactly true, as you could inject `foos..bars RESAMPLE EVERY 5m FOR 12w` as `database` parameter ;-)

What do you think of this method signature extension:

```ruby
def create_continuous_query(name, database, query, resample: nil)
```

where you call it as:

```ruby
client.create_continuous_query "hourly_level_last_month", "water_level",
  "SELECT ...",
  resample: "EVERY 5m FOR 4w"

client.create_continuous_query "monthly_level", "water_level",
  "SELECT ...",
  resample: "EVERY 1h"
```

?

**Comment by jeffdeville** [comment]
lol! Fair enough.

Here's my thinking on this.  I worked around it by just dropping down to calling client.query(full CQ). Honestly, I think that's probably all you need, because the syntax is distinct enough that you really have to hit the docs to understand what you're passing in anyway, so having to understand the string, and then somewhat arbitrarily then splitting it up to fit a template seems like it just makes you have to learn 2 things instead of 1. 

So if it was me, and I didn't have to worry about backward compatiblity or anything, I'd probably just alias the method to 'execute', and leave it to the user.  That said, if you want to maintain compatibility, then I'd suggest the parameters resample_every:nil and resample_for: nil.

But I'd be content w/ your solution as well.

**Comment by jeffdeville** [comment]
Side question: Do you have any suggestions on how to test these CQ's?  I'm in kind of a painful place where I have to:  create the cq, load a massive amount of data, and then wait an hour to see if it worked. I can't think of any other way to do it, but if you do, please enlighten me!

**Comment by dmke** [comment]
Yeah, the CQ syntax indeed requires reading the docs, and I agree: the step to `execute`'ing your own query isn't that far. But I guess for the sake of completeness, we should extend `create_continuous_query` (in a somewhat backward compatible way).

I'll implement your suggestion (`resample_every` + `resample_for`) later, when I'm home.

Regarding your testing question: I honestly don't know, I just maintain the Ruby gem :-) You may want to ask at [influxdata/influxdb](https://github.com/influxdata/influxdb/issues) or on the [mailing list](groups.google.com/forum/#!forum/influxdb).

**Comment by dmke** [comment]
Version 0.3.3 is [now available](https://rubygems.org/gems/influxdb/versions/0.3.3).
