### ISSUE TITLE
Shouldn't need to pass database name if provided in config

### ISSUE THREAD

**Issue by anthonator** [influxdata/influxdb-ruby#153]
I shouldn't have to pass in the database name to `create_database` or `delete_database` if I provide `database` in the config.

**Comment by dmke** [comment]
I'm a bit busy this week, so if you want to create a PR, I'll merge it in.

**Comment by anthonator** [comment]
Opened https://github.com/influxdata/influxdb-ruby/pull/154

**Comment by dmke** [comment]
Thanks, merged and released as [v0.3.5](https://rubygems.org/gems/influxdb/versions/0.3.5).
