### ISSUE TITLE
Timestamps in microsecond or second format?

### ISSUE THREAD

**Issue by retorquere** [influxdata/influxdb-ruby#156]
I'm trying to write timestamped data such as

```
"car", {:values=>{:G_sensor_long=>0}, :tags=>{:id=>"1", :trip=>"1444745773000"}, :timestamp=>1444745773200}
```

but for this timestamp I get this error using influxdb-ruby (import via curl works fine)

```
time outside range 1677-09-21 00:12:43.145224192 +0000 UTC - 2262-04-11 23:47:16.854775807 +0000 UTC"
```

and when I pass fractional seconds using

```
"car", {:values=>{:G_sensor_long=>0}, :tags=>{:id=>"1", :trip=>"1444745773000"}, :timestamp=>1444745773.200}
```

I get 

```
bad timestamp
```

**Comment by retorquere** [comment]
Never mind, I found it, setting precision to `u`

**Comment by dmke** [comment]
Indeed.

The default precision in the Ruby client is seconds (`"s"`).

HTH, Dominik
