### ISSUE TITLE
Write to Series or Measurements

### ISSUE THREAD

**Issue by lxxdn** [influxdata/influxdb-ruby#158]
Hi,  I'm new to influxdb. 

I've got question that from the inflxudb documentation v0.13, the `write` API is always writing to a certain measurement. 

While from the influxdb gem, it's always talking about writing to a series. 

Is there any difference? Thanks!

**Comment by dmke** [comment]
Yeah, measurements and series mean the same thing in this Gem.

My guess is, that this is a leftover from the 0.8-to-0.9 transition (when InfluxDB itself has had a change in that area). I'm willing to add code which accepts both `series` and `measurement` as hash key for a data point (and deprecate the `series` key). A pull request has a high propability to get merged ;-)

(note to self: #152)
