### ISSUE TITLE
Cannot write nulls to the database

### ISSUE THREAD

**Issue by retorquere** [influxdata/influxdb-ruby#159]
If I try to pass a point like this to write_points, I get an error (the payload generator generates `GPS.city=`)

```
{ timestamp: point['time'], series: 'car', tags: { license: tags['license'] }, values: { 'GPS.city' => nil } }
```

**Comment by dmke** [comment]
Currently, that's intended: you simply cannot store null values. (I've stumbled upon thi myself, see influxdata/influxdb#6150).

For the moment, I recommend using something `.select{|_,v| !v.nil? }` (or `.compact` if ActiveSupport is available) on the hash you pass to `write_point`/`write_points`.

If you *really* need this in several places and projects, we could discuss an `omit_nil_values` option for `InfluxDB::Client`.

**Comment by retorquere** [comment]
It's more that I actively want to overwrite existing values with nulls.
Some values that come into the database are invalid data on analysis, and
I'm looking for a way to remove them or to mark them as invalid.

**Comment by dmke** [comment]
I see.

Maybe it's easier to store raw and analyzed data in different measurements (that is what I do)?

**Comment by retorquere** [comment]
I have that (of sorts), but it would still require recalculation of the whole (quite large) derived measurement when the algorithm changes for any one of the fields. But if InfluxDB doesn't allow for it, there's nothing much the ruby interface can do.

**Comment by dmke** [comment]
Indeed. Maybe influxdata/influxdb#6150 is too broad and you should to file a different issue.
