### ISSUE TITLE
Positional parameter queries do not properly escape placeholders in AS clauses

### ISSUE THREAD

**Issue by WilHall** [influxdata/influxdb-ruby#163]
A simple example of this issue can be seen with the following query:
`query = "SELECT %{1} AS %{2} FROM "database" GROUP BY LIMIT 10"`

executed as:
`InfluxDB::Client.new.query query, params: [:numMeasurements, :foobar]`

which will yield the error:
`influxdb/client/http.rb:84:in 'resolve_error': {"error":"error parsing query: found foobar, expected identifier at line 1, char 28"} (InfluxDB::Error)`

and generates the following query:
`SELECT 'numMeasurements' AS 'foobar' FROM "database" GROUP BY LIMIT 10`

This is incorrect according to the [InfluxDB documentation](https://docs.influxdata.com/influxdb/v0.9/query_language/query_syntax/#identifiers-double-quoted), which states that identifiers should be double-quoted (in this case, both placeholders require double quotes).

**Comment by dmke** [comment]
The implementaion for positional (and named) parameters is currently very naïve and only supports escaping for *field and tag values*, i.e.

```ruby
q = "SELECT * FROM "database" WHERE foo = %{1} and bar > %{2}"
client.query q, params: ["a string", 42]
#=> SELECT * FROM "database" WHERE foo = 'a string' and bar > 42
```

Anything fancier needs a rewrite/extension of `InfluxDB::Query::Builder`. I have something like this in mind:

```ruby
q = client.select("*").from(:database).where("foo = %{1} and bar > %{2}", "a string", 42).group(time: "1h")
q.execute
#=> SELECT * FROM "database" WHERE foo = 'a string' and bar > 42 GROUP BY time(1h)
```

As I said, this is not yet possible with this Gem, but if you're using Rails, you can achive something similar today with [Influxer](https://github.com/palkan/influxer).
