### ISSUE TITLE
Migrate smoke tests to RSpec

### ISSUE THREAD

**Issue by dmke** [influxdata/influxdb-ruby#170]
As mentioned in https://github.com/influxdata/influxdb-ruby/issues/152#issuecomment-253354260, the smoke tests in the `smoke/` directory are in need of improvement.

Currently, the smoke test suite is simply a collection of Ruby files, which are executed in the [`smoke` Rake task](https://github.com/influxdata/influxdb-ruby/blob/10945de3ba49c370c42083fcb64392d08075dedc/Rakefile#L17-L19). meaning any of the expected goodies like a set up/tear down mechanism, assertions simply don't exist. To get around this, the `smoke/noaa-sample-data.rb` has a `test_case` method, which is more of a bad joke...

This hacky solution exists, because I didn't want to run the smoke tests, when a user simply executes `rake` or `rspec` in the Gem's root directory, but only when certain conditions are met (like `ENV["travis"] == "true"` indicating a CI server), _and_ because filtering the file list in the `specs/spec_helper.rb` was even more of an adventure. 

In retrospect, an `.rspec` file with an `--exclude` pattern might have been enough.

---

Your task, should you choose to accept it, would be:
- moving the smoke test files from `smoke/` to `specs/smoke/` and converting them to RSpec specs
- moving the `smoke/provision.sh` to a more appropriate place (root dir would be okay, I guess)
- finding a way to automatically exclude `spec/smoke/**/*.rb` when invoking any of these commands:
  - `rake` and `rake spec`
  - `rspec` and `rspec ./spec`
    This should generate a visible warning when `ENV["travis"] != "true"` (and not run the smoke tests):
  - `rspec ./spec/**/*` or `rspec ./spec/smoke`

You will probably need/want to run the smoke tests on your local machine. To do that, install a current version of InfluxDB locally, and create the following users and databases (this is extracted from the `smoke/provision.sh`:

``` sql
CREATE USER root WITH PASSWORD 'toor' WITH ALL PRIVILEGES
CREATE USER test_user WITH PASSWORD 'resu_tset'
CREATE DATABASE db_one
CREATE DATABASE db_two
GRANT ALL ON db_two TO test_user
GRANT ALL ON NOAA_water_database TO test_user
```

Then download and import the NOAA sample data set:

``` sh
curl https://s3-us-west-1.amazonaws.com/noaa.water.database.0.9/NOAA_data.txt > noaa.txt
influx -import -path noaa.txt -precision s
```

and enable HTTP authentication in `/etc/influxdb/influxdb.conf` (`auth-enabled = true` in the `[http]` section). Finally restart the server (`systemctl restart influxd.service` on Debian)

**Comment by TheKaterTot** [comment]
I'd like to work on this. Are there any updates I need to know about? It seems relatively straightforward.

**Comment by dmke** [comment]
Hey, thanks for taking this on :-)

I don't believe there are any major updates impacting this task. Do you have/want write access to this repo?

**Comment by TheKaterTot** [comment]
I don't have write access, but that would be great.

**Comment by dmke** [comment]
You should now be able to push into this repo.

Let me know if you're stuck.

**Comment by TheKaterTot** [comment]
Merged! Thanks @dmke
