### ISSUE TITLE
Possibly broken Unicode support in latest gem version

### ISSUE THREAD

**Issue by spijet** [influxdata/influxdb-ruby#171]
Hello everyone! First of all, big thanks to you people for making this gem!  I use it in my small SNMP collector to send data to InfluxDB, and it worked great so far.
Sadly, after upgrading it in my collector's bundle not so long ago, I got an issue with non-latin text in tag values: instead of sending Unicode characters as-is (as it did before and it worked perfectly), it appears to strip all non-ASCII characters from tags.

Here's an example of a data point I send to write_points():
```
{:series=>"snmp_if_mcast_tx", :values=>{:value=>1}, :tags=>{:hostname=>"172.30.39.85", :title=>"БВК(30-39-85)", :city=>"Улан-Удэ", :group=>"КЛМ", :instance=>"1/26", :subinstance=>"none"}, :timestamp=>1477974808894410240}
```

And here's what I get on InfluxDB host (ripped it out of UDP stream using wireshark):
```
snmp_if_traffic_tx,hostname=172.30.39.85,title=(30-39-85),city=-,instance=1/26,subinstance=none value=59194146i 1477973457361291264
```

The issue appeared after updating the gem (here's the diff of Gemfile.lock):
```
-    influxdb (0.3.8)
+    influxdb (0.3.11)
```

**Comment by spijet** [comment]
I tried the code added by #169 in `irb`, it seems to be the source of this issue:

```
irb(main):001:0> city = "Улан-Удэ"
=> "Улан-Удэ"
irb(main):002:0> city.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
=> "-"
```

I'll downgrade to 0.3.10 for now.

**Comment by dmke** [comment]
Thank you for reporting this.

Are you okay with an opt-out config option, like

``` ruby
cli = InfluxDB::Client.new db, enforce_utf8: false
```

with the default being `true`?

Alternatively, you can force UTF8 encoding on your end:

``` ruby
# assuming KOI8-R here, substitute with your own
"Улан-Удэ".force_encoding("KOI8-R").encode("UTF-8")
```

**Comment by spijet** [comment]
Thanks for fast answer!

This option looks like a good way for now, until there's a way to filter
out bad UTF chars without killing non-latin letters.

About KOI8-R -- it's reaaaally rare these days, especially in new
products. Sometimes it could be found in emails though. :)

Dominik Menke <notifications@github.com> writes:

> Thank you for reporting this.
>
> Are you okay with an opt-out config option, like
>
> cli = InfluxDB::Client.new db, enforce_utf8: false
>
> with the default being true?
>
> Alternatively, you can force UTF8 encoding on your end:
>
> # assuming KOI8-R here, substitute with your own
> "Улан-Удэ".force_encoding("KOI8-R").encode("UTF-8")
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Сергей Ткачук
Инженер Отдела Эксплуатации Сети Доступа
Компания ТрансТелеКом МР Сибирь (регион Иркутск)

**Comment by dmke** [comment]
I believe an encoding conversion from UTF-8 to UTF-8 should do the trick: https://github.com/influxdata/influxdb-ruby/commit/c93ef912e6b5b535002d6ebeb1235a5aae7c54ec

I'm waiting for Travis to complete and will issue a new release then.

**Comment by dmke** [comment]
Hm. The spec breaks on MRI 1.9 and 2.0... I will have a more detailed look later, when I'm home again.

**Comment by dmke** [comment]
Sorry for the late response, I totally forgot about this issue.

When I'm home later, I'll finally take care of this...

**Comment by dmke** [comment]
So, I have pushed a 0.3.12 release to Rubygems.

Please note that the Unicode support on MRI 1.9 and 2.0 is a bit flaky, so you're on your own if you find an error on those version, which are absent in MRI 2.1 or later.

**Comment by spijet** [comment]
Thanks a lot! I'll try to take some time and test it today. :)

As for MRI -- I mostly use MRI 2.2 and 2.3, so it's ok.

Dominik Menke <notifications@github.com> writes:

> So, I have pushed a 0.3.12 release to Rubygems.
>
> Please note that the Unicode support on MRI 1.9 and 2.0 is a bit flaky, so
> you're on your own if you find an error on those version, which are absent in
> MRI 2.1 or later.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Serge Tkatchouk
