### ISSUE TITLE
Scrubbing strings breaks emoji

### ISSUE THREAD

**Issue by zezuladp** [influxdata/influxdb-ruby#174]
emoji's for json for writing end up being empty when scrubbing them according to changelog:

- Bugfix/Enhancement in `PointValue#escape`. Input strings are now scrubbed

It works for me on 0.3.10 but not 0.3.11 i'm assuming this is why

**Comment by dmke** [comment]
Does this occur on 0.3.12 as well?

**Comment by zezuladp** [comment]
Looks like 0.3.12 does work. Thanks!
