### ISSUE TITLE
Logging every check to background queue is overkill

### ISSUE THREAD

**Issue by chrisarcand** [influxdata/influxdb-ruby#180]
Stemming from discussions [here](https://github.com/influxdata/influxdb-rails/issues/35), even when that separate issue is resolved and logging is working as expected, I think the logging located in [`Writer::Async#check_background_queue`](https://github.com/influxdata/influxdb-ruby/blob/fa3c3f0b404aa87d8faa2272e556b884e3c961cd/lib/influxdb/writer/async.rb#L96-L97) is simply overkill for most users of the client. In any environment (such as as Rails console, but anywhere really) when workers are started it creates an unstoppable mess in the logs or your STDOUT with the polling. 

I would submit a PR to simply remove this, but I respect that it might be exceedingly useful in other contexts, like working on this gem in general. Is there some way we can specify a `verbose` setting or some such to (by default) turn off this incessant logging of polls? 

Simply setting the logger to something other than `DEBUG` seems unhelpful, as (again, given something like a Rails console) I want to see debug-like messages from other gems/the application, just not this polling. Any other thoughts?

**Comment by chrisarcand** [comment]
cc/ @dmke

**Comment by dmke** [comment]
Thanks for opening this here as well.

Adding a `verbose` config option sounds like a good idea. It should default to `true` here, but is set to `false` by the Rails gem. This allows to keep the current behaviour for non-Rails consumers.

**Comment by dmke** [comment]
We now have a seperate log level declaration in `InfluxDB::Logging.log_level`, defaulting to `Logger::INFO` and decreasing the noise in your logs.

To re-enable this client's logs, you'll need to setup

```ruby
InfluxDB::Logging.log_level = Logger::DEBUG
```

A config option is not possible, since we use a global logger instance (which influxdb-rails uses to hook into).
