### ISSUE TITLE
Add list_series and delete_series methods to Client

### ISSUE THREAD

**Issue by wrocla** [influxdata/influxdb-ruby#183]
It would be nice to have list_series and delete_series methods on Client, 
like list_databases or delete_database. 

e.g.:
```
influxdb = InfluxDB::Client.new ENV['INFLUXDB_DATABASE'], ['INFLUXDB_USERNAME'], ['INFLUXDB_PASSWORD']
influxdb.list_series
influxdb.delete_series(series_name)
```

I made PR in two versions.
https://github.com/influxdata/influxdb-ruby/pull/184
 - add execute_db to Query::Core

https://github.com/influxdata/influxdb-ruby/pull/185
 - modify execute method in Query::Core

**Comment by dmke** [comment]
Cool!

I'll have a look later, when I'm back home (was just about to get to work).

**Comment by dmke** [comment]
I'm in favour of #185 (i.e. I don't like the additional `execute_db` method).

I have some comments though, which I'm going to add over there.
