### ISSUE TITLE
Minute precision raises influxDB error

### ISSUE THREAD

**Issue by patrobinson** [influxdata/influxdb-ruby#187]
Steps to reproduce:

```
@conn = InfluxDB::Client.new(
          database: ENV['DB_NAME'],
          host: ENV['INFLUX_HOSTNAME'],
          port: ENV['INFLUX_PORT']
        )
data = {
  values: { value: 0 },
  timestamp: Time.now.to_i
}
name = 'foobar'
precision = 'm'
@conn.write_point(name, data, precision)
```

Result:
```
InfluxDB::Error: {"error":"unable to parse 'foobar value=0i 1492056063': time outside range -9223372036854775806 - 9223372036854775806"}

	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:85:in `resolve_error'
	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:35:in `block in post'
	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:53:in `connect_with_retry'
	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:26:in `post'
	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/query/core.rb:78:in `write'
	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/query/core.rb:57:in `write_points'
	from /usr/local/bundle/gems/influxdb-0.3.14/lib/influxdb/query/core.rb:67:in `write_point'
	from (irb):16
	from bin/console:14:in `<main>')
```

Expected result:
```
=> #<Net::HTTPNoContent 204 No Content readbody=true>
```

**Comment by dmke** [comment]
Hm, interesting. Which server version are you running?

`Time.now.to_i` is a time representation in *seconds*, you might need to divide it by 60. Internally, the server converts timestamps it back to nano seconds; yet 1492056063m \* 60s/m \* 10\*\*9ns/s = ~1.5 \* 10\*\*18ns is still in range...

**Comment by patrobinson** [comment]
Server version is 1.2

I tried `1492056000` as well for a timestamp and it still failed

**Comment by dmke** [comment]
1492056063/60 = 24867600 ;-)

**Comment by dmke** [comment]
> 1492056063m \* 60s/m \* 10\*\*9ns/s = ~1.5 \* 10\*\*18ns

Oops. This is actually ~9 \* 10\*\*19ns (which is about twice as much as 2\*\*63, the max. value for timestamps in Go).

So, if you want to use *minute precision*, you'll **need** to provide timestamps reflecting this (`Time.now.to_i/60`).

**Comment by patrobinson** [comment]
Some documentation about this would be nice

**Comment by dmke** [comment]
I agree. I'd also like something like this to work out of the box:

```ruby
data = { values: { value: 0 }, timestamp: Time.now }
@conn.write_point("foobar", data, "m")
#=> POST /write
#   foobar value=0i 24867600
```

**Comment by dmke** [comment]
FYI, this should make things a bit more clear: https://github.com/influxdata/influxdb-ruby/compare/6d4ab99...c2b418b
—Dominik
