### ISSUE TITLE
Can client's host-name have slash?

### ISSUE THREAD

**Issue by deokjinkim** [influxdata/influxdb-ruby#191]
Hello, I'm newbie to influxdb :)
I have a question about client's host-name.

I want to use "XXX.XXX.XXX.XXX:YYYY/foo/bar" as client's host-name.
* XXX.XXX.XXX.XXX => IP Address
* YYYY => Port

When I tried below code, I met error.
1. code
influxdb = InfluxDB::Client.new database, host: "XXX.XXX.XXX.XXX:YYYY/foo/bar"

2. error log
/var/lib/gems/2.3.0/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:85:in `resolve_error': 400 Bad Request: malformed Host header (InfluxDB::Error)
	from /var/lib/gems/2.3.0/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:19:in `block in get'
	from /var/lib/gems/2.3.0/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:53:in `connect_with_retry'
	from /var/lib/gems/2.3.0/gems/influxdb-0.3.14/lib/influxdb/client/http.rb:11:in `get'
	from /var/lib/gems/2.3.0/gems/influxdb-0.3.14/lib/influxdb/query/core.rb:28:in `query'
	from influxdb.rb:15:in `<main>'

Currently slash('/') is not allowed for host-name? If then, is there another method to use slash?
Otherwise I have to use domain-name such as "influxdb.domain.com"?

I hope to hear your feedback.
Thank you in advance.

Best Regards,
Deokjin Kim

**Comment by dmke** [comment]
The value for `host` option must be either a domain name or an IP address. To configure a port (other than 8086), you need to provide the `port` option:

    cli = InfluxDB::Client.new host: "127.0.0.1", port: 7000

A path is not supported.

May I ask about you use case?

**Comment by dmke** [comment]
Closing this for now.
