### ISSUE TITLE
support webmock 3.0

### ISSUE THREAD

**Issue by pravi** [influxdata/influxdb-ruby#197]
We'd like to use wbmock 3.0 in debian, but influxdb tests are failing currently

full test log here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867645

**Comment by dmke** [comment]
Thanks, I will have a look later.

**Comment by dmke** [comment]
We're currently relying on Webmock 2.x because we (still) support Ruby 1.9.

However, I'm in the process of creating a (propably last) release in the 0.3.x series. Going forward, I'll bump the Ruby requirement. Since MRI 2.1 is EOL already, I might require 2.2+ for this gem.

**Comment by dmke** [comment]
I've updated the code to run with Webmock 3.0.1. Tomorrow evening (UTC+2), I'll release v0.4.0 with those changes into the wild.

**Comment by dmke** [comment]
By the way, the failing version in the bug report is 0.2.3 (released Oct '15). Since v0.3.9 (Sep '16) this gem is compatible with Webmock 3.

I suggest pulling in at least those changes into git://anonscm.debian.org/pkg-ruby-extras/ruby-influxdb.git

**Comment by pravi** [comment]
@dmke thanks! I will update the package.

**Comment by pravi** [comment]
Just updated to 0.3.16.
