### ISSUE TITLE
Query Parse Error when submitted via influxdb-ruby

### ISSUE THREAD

**Issue by cschneid** [influxdata/influxdb-ruby#201]
I’m using the Ruby InfluxDB API. This query fails to parse when executed via this gem.

Oddly, editing an unrelated part of the query from the parse error causes it to succeed.

The query works (with or without the edit mentioned below) in the InfluxDB cli tool. 

## The query:

```
SELECT SUM(call_count) as call_count, SUM(call_time) as total_call_time, MAX(max_call_time) as max_call_time, MEAN(percentile_95th) as percentile_95th
  FROM org_1.dbmetrics.dbmetrics_1
  WHERE 
    time >= 1507136400s
    AND time < 1507741200s
    AND (app = '6')
    AND ((model_name = 'Request' AND operation = 'save') OR (model_name = 'Request' AND operation = 'find'))
  GROUP BY model_name,operation,scope
```

(the query does have newlines, and everything is spaces, no hard tabs).

Error when run via the gem:

```
{"error":"error parsing query: found ), expected identifier, string, number, bool at line 7, char 10"}
```

## The odd part:

* If I remove scope from the GROUP BY, the query works.
* If I run the query directly via Influx console, the query works.

Wrapping `scope` in double quotes has no impact, and nothing here appears to be a reserved keyword.

I’m running InfluxDB version 1.2.0 on OSX and the influxdb ruby gem is version 0.3.16.

**Comment by itsderek23** [comment]
Also tested against Influx 1.3.6 - same result.

**Comment by dmke** [comment]
Interesting. I'm on my way home and will have a look in a moment.

Do you have a few data points I can use locally to reproduce this? (If you don't want to publish them, you can send them privately to `dominik.menke [at] gmail.com`)

**Comment by dmke** [comment]
So far, I can't reproduce this behaviour: this [smoke test](https://github.com/influxdata/influxdb-ruby/blob/issue201/smoke/issue201.rb) runs successfully against multiple InfluxDB server versions: https://travis-ci.org/influxdata/influxdb-ruby/builds/287200331

Did you try the latest gem version? Which Ruby version are you running?

**Comment by dmke** [comment]
@cschneid, @itsderek23 Any news?

**Comment by cschneid** [comment]
We ended up reformulating the query, and have moved on. No real resolution, but I'll close. Thank you

**Comment by dmke** [comment]
Ok, no problem. Thanks for letting me know.

**Comment by maxp-edcast** [comment]
I noticed that when passing a heredoc to `.query` it doesn't work if it has newlines, they need to be escaped but _not_ before a close parenthesis

```
query = <<-TXT

  SELECT SUM(call_count) as call_count, SUM(call_time) as total_call_time, MAX(max_call_time) as max_call_time, MEAN(percentile_95th) as percentile_95th \
  FROM org_1.dbmetrics.dbmetrics_1 \
  WHERE \
    time >= 1507136400s \
    AND time < 1507741200s \
    AND (app = '6') \
    AND (  \
      (model_name = 'Request' AND operation = 'save') \
      OR \
      (model_name = 'Request' AND operation = 'find')
    ) \
   GROUP BY model_name,operation,scope

TXT
```

**Comment by dmke** [comment]
Huh, that's a weird, new issue. Are you 100% positive, you don't do any further post-processing on that string?

**Comment by dmke** [comment]
I've updated the [repro code](https://github.com/influxdata/influxdb-ruby/blob/issue201/spec/smoke/issue201_spec.rb), and at least I get it to break on Travis now.

Will investigate further tomorrow, today was a long day :-)

**Comment by dmke** [comment]
That failure on Travis was related to a missing database (again... long day...).

Here's what it currently looks like: https://travis-ci.org/influxdata/influxdb-ruby/jobs/341190751#L637.

**Comment by dmke** [comment]
@maxp-edcast Did you, by any chance, write the query in a CRLF environment (Windows)?

**Comment by maxp-edcast** [comment]
@dmke no, wrote it on OSX. We probably do some postprocessing. You can disregard my last comment. I apologize for coming here and spreading misinformation.

**Comment by dmke** [comment]
Oh, don't worry, I like interesting puzzles :-D
