### ISSUE TITLE
List retention policies errors out on database with no retention policies at all?

### ISSUE THREAD

**Issue by djoos** [influxdata/influxdb-ruby#213]
Hi there,

I'm making use of a Chef cookbook that relies on this InfluxDB Ruby client to perform operations on InfluxDB. When [checking if retention policies exist on a database](https://github.com/bdangit/chef-influxdb/blob/master/resources/retention_policy.rb#L42) and the database doesn't have any, not even the autogen one, `client.list_retention_policies` errors out with `NoMethodError: undefined method `map' for nil:NilClass` on [this line](https://github.com/influxdata/influxdb-ruby/blob/426497ac86527b1e93b8046f053310f6fb8c3469/lib/influxdb/query/retention_policy.rb#L22).

Perhaps it would be a good idea to [fetch](https://github.com/influxdata/influxdb-ruby/blob/426497ac86527b1e93b8046f053310f6fb8c3469/lib/influxdb/query/retention_policy.rb#L20) with a default?

Thanks in advance!
David

**Comment by dmke** [comment]
Good catch! I will have a look when I'm back home.
