### ISSUE TITLE
Issue when writing a tag value ending in a back slash

### ISSUE THREAD

**Issue by metal-hed** [influxdata/influxdb-ruby#225]
This is related to https://github.com/influxdata/influxdb/issues/5231 seems when a tag value ends in a `\` , influx rejects the insert statement. I have seen other clients work around this by adding a space to the end of the tag value such as the python client

https://github.com/influxdata/influxdb-python/pull/537/commits/051da0c9d3d5657a98e124efcafbceb19b310318

is this something that can be done in this plugin as well?

**Comment by dmke** [comment]
Sure, the serialization happens in [`lib/influxdb/point_value.rb`](https://github.com/influxdata/influxdb-ruby/blob/master/lib/influxdb/point_value.rb). If you want to give it a go, I'll merge your PR.

(Otherwise I need to find time to do this myself, and that's currently a scarce resource).

**Comment by metal-hed** [comment]
I can give it a go, will open a PR in the next few days.

**Comment by dmke** [comment]
I've found some time and fixed it (after wrestling with travis and bundler...) :-)

Will release a new version soon.

**Comment by metal-hed** [comment]
Wow amazing! I was going to take a look this afternoon but this is great

Thanks!
