### ISSUE TITLE
Identify repo owner and move to InfluxCommunity org

### ISSUE THREAD

**Issue by mhall119** [influxdata/influxdb-ruby#261]
The v1 client libraries for InfluxDB were typically developed and maintained by community members. They have all now been succeeded by v2 client libraries developed and maintained by InfluxData in partnership with Bonitoo.

If there are still users of this v1 client library, and they or somebody else are willing to keep them updated with security fixes at a minimum, this code should be moved to https://github.com/InfluxCommunity and control of it given to the new maintainers. Otherwise let's archive it in favor of the v2 client library.

**Comment by dentarg** [comment]
Just dropping the link to v2: https://github.com/influxdata/influxdb-client-ruby

**Comment by Esity** [comment]
I will gladly take ownership of this one, Already have access to push the gem to rubygems @mhall119

**Comment by Anaisdg** [comment]
@Esity thank you for taking ownership of this, we really appreciate it. It has been moved to InfluxCommunity.

**Comment by ChrisBr** [comment]
@Anaisdg & @mhall119  👋 and nice to meet you. 

> control of it given to the new maintainers.

@hennevogel and I have put quite some significant work into this and influxdb-rails gem so it's a bit harsh to come in and request this gem gets transferred to new maintainers (who not even have contributed to the gem). That's an interesting take of influxdb on open source.
