### ISSUE TITLE
why not using symbols in query results

### ISSUE THREAD

**Issue by SaeedHK** [influxdata/influxdb-ruby#262]
Since [it's known](https://stackoverflow.com/questions/8189416/why-use-symbols-as-hash-keys-in-ruby/8189435#8189435) that symbols are better performant than strings as `Hash` keys, I was wondering if there is a good reason having strings in the query results of `InfluxDB::Client` ?

I am new to Ruby so it's very likely that I am missing something. Appreciate any help around this question !

**Comment by bednar** [comment]
Hi @SaeedHK,

Thank you for choosing our client and for bringing your performance concerns to our attention. The use of `Hash` keys within the client is indeed based on historical decisions made during the initial stages of development. We acknowledge that there may be room for optimization and improvement in this area.

We highly value the feedback and contributions from our user community. If you, or anyone else, have suggestions or enhancements, particularly regarding the use of `Hash` keys or any other performance improvements, we encourage you to share them with us.

Please feel free to submit a Pull Request with your proposed changes. We look forward to seeing your suggestions and are here to assist you through the contribution process if needed.

Best Regards.
