### ISSUE TITLE
In #write_point, it's not possible to override time_precision and not async

### ISSUE THREAD

**Issue by Peeja** [influxdata/influxdb-ruby#57]
Because of the way it's defined,

```ruby
def write_point(name, data, async=@async, time_precision=@time_precision)
```

there's no way to specify a `time_precision` without also specifying whether to use async or not. So far, I've found I'm much more likely to care about setting the precision (which can change based on what data you're writing) than deciding whether to be synchronous.

I'd suggest making them keyword arguments so either or both can be specified.

**Comment by dmke** [comment]
I believe this is fixed by now, so I'll close this issue. The async option has moved to the `InfluxDB::Client` initializer some time ago.
