### ISSUE TITLE
write_point method doesn't allow bulk load for different series

### ISSUE THREAD

**Issue by areina** [influxdata/influxdb-ruby#61]
Now, it's possible to send multiple points but only for the same serie. The http api supports it, then it would be nice add this feature to the gem. What do you think? 

I could contribute with a patch but I prefer read your opinion before. Thanks!

**Comment by palkan** [comment]
Use [write_points](https://github.com/influxdb/influxdb-ruby/blob/master/lib/influxdb/query/core.rb#L40)

**Comment by palkan** [comment]
Oh, sorry, it's been a year ago)
