### ISSUE TITLE
keep hitting "influxdb/client.rb:384:in `block in post': 404 page not found (InfluxDB::Error)"

### ISSUE THREAD

**Issue by LeonLee88** [influxdata/influxdb-ruby#91]
A latest influxdb is running on my local machine and the web UI works well, as well as the console. I am attempting to use this client lib to do some write or database creation operation to my local influxdb. However that error keeps prompting when I run any operation. Here is the most simplified script I tried.
```
require 'influxdb'

username = 'root'
password = 'root'
database = 'test_db'
name     = 'foobar'

influxdb = InfluxDB::Client.new

influxdb.create_database(database)
```
And the whole error.
```
/var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:384:in `block in post': 404 page not found (InfluxDB::Error)
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:431:in `call'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:431:in `connect_with_retry'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:375:in `post'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:94:in `create_database'
	from ./test1.rb:10:in `<main>'

```

Update:

I found the lib installed via gem install is inconsistent with the latest update in this repository. Then I replaced the lib with the latest code. Now the error changed.
```
/var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client/http.rb:95:in `resolve_error': 404 page not found (InfluxDB::Error)
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client/http.rb:33:in `block in post'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client/http.rb:65:in `call'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client/http.rb:65:in `connect_with_retry'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/client/http.rb:26:in `post'
	from /var/lib/gems/2.1.0/gems/influxdb-0.1.9/lib/influxdb/query/database.rb:8:in `create_database'
	from ./test1.rb:11:in `<main>'
```

**Comment by alpern95** [comment]
Hello,
I have the lastest influxdb 0.9.1 and the lastest gem influxdb 0.1.9
 and i have the same problem.

LOG in /var/log/sensu/server.log

 {"timestamp":"2015-07-09T14:48:46.303223+0000","level":"info","message":"handler output","handler":{"type":"pipe","command":"/etc/sensu/handlers/influxdb-metrics.rb","name":"influxdb"},"output":["/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:384:in `block in post': 404 page not found (InfluxDB::Error)\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:431:in `call'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:431:in `connect_with_retry'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:375:in `post'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:306:in `_write'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:285:in `write_points'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:253:in `write_point'\n","\tfrom /etc/sensu/handlers/influxdb-metrics.rb:33:in `block in handle'\n","\tfrom /etc/sensu/handlers/influxdb-metrics.rb:23:in `each_line'\n","\tfrom /etc/sensu/handlers/influxdb-metrics.rb:23:in `handle'\n","\tfrom /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-handler.rb:55:in `block in <class:Handler>'\n"]}

**Comment by LeonLee88** [comment]
I am annoied with this when I was trying send sensu output to influxdb(0.8). But the team seems will not do anything to fix it. Now I have to abandon using the influxdb client and use curl to write data to my db and finally make it work and display data on grafana(2.0.0 beta).

**Comment by toddboom** [comment]
@LeonLee88 @alpern95 you should use master for InfluxDB v0.9.x - the `v0.2.0` gem will be released later this weekend.

**Comment by williampratt** [comment]
One other tip, delete all of your previous gem versions just in case. I hit this before my pr due to an old version being used. Delete all versions of influxdb-ruby from your gemset and bundle install.

**Comment by alpern95** [comment]
Hello Todboom,
i have now the new gem version 0.9.1 , 
i use sensu with the handler influxdb with the command influxdb-metrics.rb.
I have now a reject from the  influxdb api.
the nex api do not accept write without TAG.
I dont know how to add a tag on the output for my metrics. 
perhaps i need to modify myself influxdb-metrics.rb?
Log sensu
(influxdb_1          | [http] 2015/07/22 17:28:36 172.17.1.89 - - [22/Jul/2015:17:28:36 +0000] POST /write?db=sensu&precision=s&u=sensu&p=pass HTTP/1.1 400 77 - Ruby 15c25a18-3097-11e5-853a-000000000000 3.144229ms)
( influxdb_1          | [http] 2015/07/22 17:27:10 10.0.163.173 - sensu [22/Jul/2015:17:27:10 +0000] POST /write?consistency=&db=sensu&precision=&rp= HTTP/1.1 204 0 - InfluxDBClient e2313ba8-3096-11e5-8514-000000000000 10.766309ms )
End Log

I have also a telegraf client who use the same base and works perfectly.

If you have an advice/idee for me Thank.

**Comment by gunnaraasen** [comment]
@toddboom looks like `v0.2.0` has been released. Is this issue fixed?

**Comment by nurettin** [comment]
@gunnaraasen I get 404 Connectivity Error with v0.2.1 and influxdb v0.9.0 on mac os x installed via home-brew.

**Comment by brodock** [comment]
it's said on the README, that you should use v0.9.1 or greater.

**Comment by dmke** [comment]
I'm going to close this for now.

Please let me know if the problem still exists in recent versions of the Rubygem.
